In [32]:
import torch
# import torch.nn as nn
# import torch.nn.functional as F
# import torch.optim as optim

In [33]:
#변수선언
x_train = torch.FloatTensor([[1],[2],[3],[4],[5],[6]])
y_train = torch.FloatTensor([[2],[4],[6],[7],[11],[14]])

#가중치, 편향초기화
#requires_grad=True는 해당 변수에 gradient값이 저장되고 업데이트 된다는 의미
w = torch.zeros(1,requires_grad=True)
b = torch.zeros(1,requires_grad=True) 

#경사하강법 구현
optimizer = optim.SGD([w,b], lr=0.01)
epochs = 20000

for epoch in range(epochs+1):

    H = x_train * w + b
    cost = torch.mean((H - y_train)**2)

    optimizer.zero_grad() #경사 0으로 초기화
    cost.backward() #비용함수 미분해서 gradient 계산
    optimizer.step() #w,b 업데이트

    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, epochs, w.item(), b.item(), cost.item()
        ))

Epoch    0/20000 W: 0.650000, b: 0.147 Cost: 70.333336
Epoch  100/20000 W: 2.126379, b: 0.060 Cost: 0.712527
Epoch  200/20000 W: 2.192670, b: -0.224 Cost: 0.626169
Epoch  300/20000 W: 2.238662, b: -0.421 Cost: 0.584604
Epoch  400/20000 W: 2.270569, b: -0.557 Cost: 0.564597
Epoch  500/20000 W: 2.292706, b: -0.652 Cost: 0.554968
Epoch  600/20000 W: 2.308064, b: -0.718 Cost: 0.550333
Epoch  700/20000 W: 2.318718, b: -0.763 Cost: 0.548102
Epoch  800/20000 W: 2.326110, b: -0.795 Cost: 0.547028
Epoch  900/20000 W: 2.331239, b: -0.817 Cost: 0.546511
Epoch 1000/20000 W: 2.334797, b: -0.832 Cost: 0.546263
Epoch 1100/20000 W: 2.337265, b: -0.843 Cost: 0.546143
Epoch 1200/20000 W: 2.338977, b: -0.850 Cost: 0.546085
Epoch 1300/20000 W: 2.340165, b: -0.855 Cost: 0.546058
Epoch 1400/20000 W: 2.340990, b: -0.859 Cost: 0.546044
Epoch 1500/20000 W: 2.341561, b: -0.861 Cost: 0.546038
Epoch 1600/20000 W: 2.341958, b: -0.863 Cost: 0.546035
Epoch 1700/20000 W: 2.342233, b: -0.864 Cost: 0.546033
Epoch 1800/

In [34]:
#변수선언
x_train = torch.FloatTensor([[1],[2],[3],[4],[5],[6]])
y_train = torch.FloatTensor([[2],[4],[6],[7],[11],[14]])

#가중치, 편향초기화
#requires_grad=True는 해당 변수에 gradient값이 저장되고 업데이트 된다는 의미
w = torch.zeros(1,requires_grad=True)
b = torch.zeros(1,requires_grad=True) 

#경사하강법 구현 - 내장함수 사용
optimizer = optim.SGD([w,b], lr=0.01)
criterion = nn.MSELoss()
epochs = 2000

for epoch in range(epochs+1):

    H = x_train * w + b
    cost = criterion(H,y_train)

    optimizer.zero_grad() #새로운 기울기를 기존 기울기에 더하는데 새로운 기울기가 누적되서 계산되지 않게
    cost.backward() #비용함수 미분해서 gradient 계산
    optimizer.step() #w,b 업데이트

    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, epochs, w.item(), b.item(), cost.item()
        ))

Epoch    0/2000 W: 0.650000, b: 0.147 Cost: 70.333336
Epoch  100/2000 W: 2.126379, b: 0.060 Cost: 0.712527
Epoch  200/2000 W: 2.192670, b: -0.224 Cost: 0.626169
Epoch  300/2000 W: 2.238662, b: -0.421 Cost: 0.584604
Epoch  400/2000 W: 2.270569, b: -0.557 Cost: 0.564597
Epoch  500/2000 W: 2.292706, b: -0.652 Cost: 0.554968
Epoch  600/2000 W: 2.308064, b: -0.718 Cost: 0.550333
Epoch  700/2000 W: 2.318718, b: -0.763 Cost: 0.548102
Epoch  800/2000 W: 2.326110, b: -0.795 Cost: 0.547028
Epoch  900/2000 W: 2.331239, b: -0.817 Cost: 0.546511
Epoch 1000/2000 W: 2.334797, b: -0.832 Cost: 0.546263
Epoch 1100/2000 W: 2.337265, b: -0.843 Cost: 0.546143
Epoch 1200/2000 W: 2.338977, b: -0.850 Cost: 0.546085
Epoch 1300/2000 W: 2.340165, b: -0.855 Cost: 0.546058
Epoch 1400/2000 W: 2.340990, b: -0.859 Cost: 0.546044
Epoch 1500/2000 W: 2.341561, b: -0.861 Cost: 0.546038
Epoch 1600/2000 W: 2.341958, b: -0.863 Cost: 0.546035
Epoch 1700/2000 W: 2.342233, b: -0.864 Cost: 0.546033
Epoch 1800/2000 W: 2.342424, 

In [17]:
#변수선언
x_train = torch.FloatTensor([[1],[2],[3],[4],[5],[6]])
y_train = torch.FloatTensor([[2],[4],[6],[7],[11],[14]])

#가중치, 편향초기화
model = torch.nn.Linear(1,1) #1,1fh 놓은 순간 자동으로 w와 b가 생성되게 됨
print(list(model.parameters()))

#경사하강법 구현 - 내장함수 사용
optimizer = optim.SGD(model.parameters(), lr=0.01)
criterion = nn.MSELoss()
epochs = 20000

for epoch in range(epochs+1):

    # H = x_train * w + b
    prediction = model(x_train)
    cost = criterion(prediction,y_train)

    optimizer.zero_grad()
    cost.backward() #비용함수 미분해서 gradient 계산
    optimizer.step() #w,b 업데이트

    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, epochs, w.item(), b.item(), cost.item()
        ))

[Parameter containing:
tensor([[0.7206]], requires_grad=True), Parameter containing:
tensor([0.9904], requires_grad=True)]
Epoch    0/20000 W: 2.342649, b: -0.866 Cost: 22.819906
Epoch  100/20000 W: 2.342649, b: -0.866 Cost: 0.962424
Epoch  200/20000 W: 2.342649, b: -0.866 Cost: 0.746450
Epoch  300/20000 W: 2.342649, b: -0.866 Cost: 0.642497
Epoch  400/20000 W: 2.342649, b: -0.866 Cost: 0.592462
Epoch  500/20000 W: 2.342649, b: -0.866 Cost: 0.568380
Epoch  600/20000 W: 2.342649, b: -0.866 Cost: 0.556788
Epoch  700/20000 W: 2.342649, b: -0.866 Cost: 0.551209
Epoch  800/20000 W: 2.342649, b: -0.866 Cost: 0.548524
Epoch  900/20000 W: 2.342649, b: -0.866 Cost: 0.547231
Epoch 1000/20000 W: 2.342649, b: -0.866 Cost: 0.546609
Epoch 1100/20000 W: 2.342649, b: -0.866 Cost: 0.546310
Epoch 1200/20000 W: 2.342649, b: -0.866 Cost: 0.546166
Epoch 1300/20000 W: 2.342649, b: -0.866 Cost: 0.546096
Epoch 1400/20000 W: 2.342649, b: -0.866 Cost: 0.546063
Epoch 1500/20000 W: 2.342649, b: -0.866 Cost: 0.546

+ 1번 코드는 가중치(w,b)와 모델설계(H), loss(cost)를 전부 수동으로 작성했다.
+ 2번 코드에서는 loss 부분을 내장함수인 MSELoss로 변환하였다.
+ 3번 코드에서는 가중치와 모델설계 부분을 내장함수인 nn.Linear(1,1)로 바꾸었다.

3번에서 주의해야 할게 있다면 optim이 기존에는 [w,b]를 수정하도록 작성되있는데 이를
자동으로 생성되는 w,b를 가리키는 model.parameter()로 바꿔야 된다는 것이다.

In [35]:
#자동미분 기능 알아보기
a = torch.tensor(2.0, requires_grad=True)
b = torch.tensor([2.0,3.0,4.0],requires_grad=True)
c = torch.tensor([[1.0,2.0],[3.0,4.0]],requires_grad=True)

x = 2*a**2 + 5
y = 2*b**2 + 5
z = 2*c**2 + 5

x.backward()
y.backward(torch.ones_like(b))
z.backward(torch.ones_like(c))

print(a.grad)
print(b.grad)
print(c.grad)

tensor(8.)
tensor([ 8., 12., 16.])
tensor([[ 4.,  8.],
        [12., 16.]])


In [9]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 80],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152],[185],[180],[196],[142]])
print(x_train.shape)
print(y_train.shape)

torch.Size([5, 3])
torch.Size([5, 1])


In [15]:
model = torch.nn.Linear(3,1)
#경사하강법 구현 - 내장함수 사용
optimizer = optim.SGD(model.parameters(), lr=1e-5)
criterion = nn.MSELoss()
epochs = 50

for epoch in range(epochs+1):

    # H = x_train * w + b
    prediction = model(x_train)
    cost = criterion(prediction,y_train)

    optimizer.zero_grad()
    cost.backward() #비용함수 미분해서 gradient 계산
    optimizer.step() #w,b 업데이트


    print('Epoch {:4d}/{} W: {:3f}, b: {:.3f} Cost: {:.6f}'.format(
        epoch, epochs, w.item(), b.item(), cost.item()
    ))

Epoch    0/50 W: 2.342649, b: -0.866 Cost: 48910.714844
Epoch    1/50 W: 2.342649, b: -0.866 Cost: 15725.843750
Epoch    2/50 W: 2.342649, b: -0.866 Cost: 5059.868652
Epoch    3/50 W: 2.342649, b: -0.866 Cost: 1631.707642
Epoch    4/50 W: 2.342649, b: -0.866 Cost: 529.858826
Epoch    5/50 W: 2.342649, b: -0.866 Cost: 175.710663
Epoch    6/50 W: 2.342649, b: -0.866 Cost: 61.881691
Epoch    7/50 W: 2.342649, b: -0.866 Cost: 25.293985
Epoch    8/50 W: 2.342649, b: -0.866 Cost: 13.532263
Epoch    9/50 W: 2.342649, b: -0.866 Cost: 9.749950
Epoch   10/50 W: 2.342649, b: -0.866 Cost: 8.532308
Epoch   11/50 W: 2.342649, b: -0.866 Cost: 8.138943
Epoch   12/50 W: 2.342649, b: -0.866 Cost: 8.010562
Epoch   13/50 W: 2.342649, b: -0.866 Cost: 7.967312
Epoch   14/50 W: 2.342649, b: -0.866 Cost: 7.951424
Epoch   15/50 W: 2.342649, b: -0.866 Cost: 7.944376
Epoch   16/50 W: 2.342649, b: -0.866 Cost: 7.940111
Epoch   17/50 W: 2.342649, b: -0.866 Cost: 7.936775
Epoch   18/50 W: 2.342649, b: -0.866 Cost: 

In [25]:
import torch
import numpy as np

# torch.manual_seed(777)
xy = np.loadtxt('/home/arclab/Documents/동건/rokey/data-04-zoo.csv',delimiter=',',dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]
print(x_data.shape,y_data.shape)

nb_classes = 7

(101, 16) (101, 1)


In [27]:
X = torch.tensor(x_data) #array를 tensor로 변환
Y = torch.tensor(y_data,dtype=torch.long).view(-1)
print('x_data=  ',x_data,'\n','X= ',X,'\n','y_data= ',y_data,'\n','Y= ',Y)

x_data=   [[1. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 1. 0. 1.]
 [0. 0. 1. ... 1. 0. 0.]
 ...
 [1. 0. 0. ... 1. 0. 1.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 1. 0. 0.]] 
 X=  tensor([[1., 0., 0.,  ..., 0., 0., 1.],
        [1., 0., 0.,  ..., 1., 0., 1.],
        [0., 0., 1.,  ..., 1., 0., 0.],
        ...,
        [1., 0., 0.,  ..., 1., 0., 1.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        [0., 1., 1.,  ..., 1., 0., 0.]]) 
 y_data=  [[0.]
 [0.]
 [3.]
 [0.]
 [0.]
 [0.]
 [0.]
 [3.]
 [3.]
 [0.]
 [0.]
 [1.]
 [3.]
 [6.]
 [6.]
 [6.]
 [1.]
 [0.]
 [3.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [5.]
 [4.]
 [4.]
 [0.]
 [0.]
 [0.]
 [5.]
 [0.]
 [0.]
 [1.]
 [3.]
 [0.]
 [0.]
 [1.]
 [3.]
 [5.]
 [5.]
 [1.]
 [5.]
 [1.]
 [0.]
 [0.]
 [6.]
 [0.]
 [0.]
 [0.]
 [0.]
 [5.]
 [4.]
 [6.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [3.]
 [3.]
 [2.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [6.]
 [3.]
 [0.]
 [0.]
 [2.]
 [6.]
 [1.]
 [1.]
 [2.]
 [6.]
 [3.]
 [1.]
 [0.]
 [6.]
 [3.]
 [1.]
 [5.]
 [4.]
 [2.]
 [2.]
 [3.]
 [0.]

In [28]:
model = torch.nn.Linear(16,nb_classes)
criterion = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(),lr=0.1)

In [30]:
for step in range(2001):
    optimizer.zero_grad()
    hypothesis = model(X)
    cost = criterion(hypothesis,Y)
    cost.backward()
    optimizer.step()

    prediction = torch.argmax(hypothesis,1)
    correct_prediction = (prediction == Y)
    accuracy = correct_prediction.float().mean()

    if step % 100 == 0:
        print(f"Step: {step}\tLoss: {cost.item():.3f}\tAcc: {accuracy.item():.2%}")

Step: 0	Loss: 2.027	Acc: 0.00%
Step: 100	Loss: 0.482	Acc: 87.13%
Step: 200	Loss: 0.328	Acc: 94.06%
Step: 300	Loss: 0.254	Acc: 95.05%
Step: 400	Loss: 0.209	Acc: 95.05%
Step: 500	Loss: 0.178	Acc: 96.04%
Step: 600	Loss: 0.155	Acc: 99.01%
Step: 700	Loss: 0.138	Acc: 99.01%
Step: 800	Loss: 0.124	Acc: 100.00%
Step: 900	Loss: 0.112	Acc: 100.00%
Step: 1000	Loss: 0.103	Acc: 100.00%
Step: 1100	Loss: 0.095	Acc: 100.00%
Step: 1200	Loss: 0.088	Acc: 100.00%
Step: 1300	Loss: 0.082	Acc: 100.00%
Step: 1400	Loss: 0.077	Acc: 100.00%
Step: 1500	Loss: 0.072	Acc: 100.00%
Step: 1600	Loss: 0.068	Acc: 100.00%
Step: 1700	Loss: 0.065	Acc: 100.00%
Step: 1800	Loss: 0.061	Acc: 100.00%
Step: 1900	Loss: 0.058	Acc: 100.00%
Step: 2000	Loss: 0.056	Acc: 100.00%


In [31]:
pred = torch.argmax(hypothesis,1)

for p,y in zip(pred, Y):
    print(f"[{bool(p.item() == y.item())}] Prediction: {p.item()} True Y: {y.item()}")

[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 3 True Y: 3
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 1 True Y: 1
[True] Prediction: 3 True Y: 3
[True] Prediction: 6 True Y: 6
[True] Prediction: 6 True Y: 6
[True] Prediction: 6 True Y: 6
[True] Prediction: 1 True Y: 1
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 0 True Y: 0
[True] Prediction: 1 True Y: 1
[True] Prediction: 1 True Y: 1
[True] Prediction: 0 True Y: 0
[True] Prediction: 1 True Y: 1
[True] Prediction: 5 True Y: 5
[True] Prediction: 4 True Y: 4
[True] Prediction: 4 True Y: 4
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 5 True Y: 5
[True] Prediction: 0 True Y: 0
[True] P